// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGQJ6G8NzkVbRn9g0t71bcakdW7f9HPmI',
    appId: '1:182072072004:web:e1d563589bdf805b36e911',
    messagingSenderId: '182072072004',
    projectId: 'bholavashi-7e0b8',
    authDomain: 'bholavashi-7e0b8.firebaseapp.com',
    storageBucket: 'bholavashi-7e0b8.firebasestorage.app',
    measurementId: 'G-NMTNV71VN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATDcQqjW0yRicpi8TRfZwDT377mNHkl8A',
    appId: '1:182072072004:android:3019c65ecd9c79a536e911',
    messagingSenderId: '182072072004',
    projectId: 'bholavashi-7e0b8',
    storageBucket: 'bholavashi-7e0b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_rzn_eMtL8ATANX3qztcQmTHI-njppak',
    appId: '1:182072072004:ios:2e160a8efdf4953536e911',
    messagingSenderId: '182072072004',
    projectId: 'bholavashi-7e0b8',
    storageBucket: 'bholavashi-7e0b8.firebasestorage.app',
    iosBundleId: 'com.sohojit.frontendFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_rzn_eMtL8ATANX3qztcQmTHI-njppak',
    appId: '1:182072072004:ios:2e160a8efdf4953536e911',
    messagingSenderId: '182072072004',
    projectId: 'bholavashi-7e0b8',
    storageBucket: 'bholavashi-7e0b8.firebasestorage.app',
    iosBundleId: 'com.sohojit.frontendFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGQJ6G8NzkVbRn9g0t71bcakdW7f9HPmI',
    appId: '1:182072072004:web:db545022b5ebb13c36e911',
    messagingSenderId: '182072072004',
    projectId: 'bholavashi-7e0b8',
    authDomain: 'bholavashi-7e0b8.firebaseapp.com',
    storageBucket: 'bholavashi-7e0b8.firebasestorage.app',
    measurementId: 'G-B828K6S6E8',
  );
}
